image_size: [256, 224]
seed: 42

AutoEncoder:
  nb_input_channels: 1
  nb_channels_fst_feature_map: 64
  latent_dim: 1024
  learning_rate: 6e-5
  scheduler: True
  loss_name: 'L2'
  device: 'auto'
  alpha: 1
  flag_perceptual_loss: True
  canny_edges: True
  scalar_divide_channels_fst_feature_map_for_decoder: 1
  encoder_only: False
  softmax: False
  sigmoid: False
  use_cbam: False

Dataset:
  images_directory: ''
  val_images_directory: ''
  path_dict_coordinates: ''
  path_dict_coordinates_val: ''
  
  grayscale: True

  use_PIL: True
  apply_transform: True
  apply_normalization: False

  transform:
    rot_degrees: 30
    translate: [10, 10]
    blur_kernel_size: 5
    brightness_factor: 1.
    contrast_factor: 1.
    noise_mean: 0
    noise_std: 0.1
    zoom_in_prob: 0.7
    blur_prob: 0.5
    brightness_prob: 0.5
    contrast_prob: 0.5
    noise_prob: 0
    vignetting_prob: 1
    masking_prob: 1
    vignetting_val: 70

trainer:
  batch_size: 128
  num_workers_loader: 2
  patience: 15
  num_epochs: 200
  model_save_path: 'caevl/models/trained/AutoEncoder/stageone/stageone.pth'
  compute_accuracy: False
  losses_save_dir_path: 'caevl/models/trained/AutoEncoder/stageone/losses'
  force_save: False
  save_checkpoint: 1
  save_optimizer: False